server:
  port: 8805
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SJTUSummerProj2020/springCloudConfig.git
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
