server:
  port: 8803
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,hysrix,stream,routes
zuul:
  prefix: /api
  routes:
    user-service: /myuser/**
    goods-service: /mygoods/**
    order-service: /myorder/**
    user-center: /usercenter/**
ribbon:
  eureka:
    enabled: true

