server:
  port: 8803
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
    fetch-registry: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,hysrix,stream,routes
zuul:
  prefix: /api
  routes:
    user-service:
      path: /myuser/**
      serviceId: user-service
      sensitiveHeaders: "*"
    goods-service:
      path: /mygoods/**
      serviceId: goods-service
      sensitiveHeaders: "*"
    order-service:
      path: /myorder/**
      serviceId: order-service
      sensitiveHeaders: "*"
    user-center:
      path: /usercenter/**
      serviceId: user-center
      sensitiveHeaders: "*"
    sso-server:
      path: /sso/**
      serviceId: sso-server
      sensitiveHeaders: "*"

ribbon:
  eureka:
    enabled: true

