spring:
  application:
    name: eureka-server
server:
  port: 8801
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://localhost:8802/eureka
#---
#spring:
#  profiles: eureka2
#server:
#  port: 8802
#eureka:
#  instance:
#    hostname: eureka2
#  client:
#    service-url:
#      defaultZone: http://localhost:8801/eureka
